### ISSUE TITLE
Secure cookies in the backend

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#590] opened 2020-07-12 21:35 UTC
Currently the backend sets cookies (`httpOnly` option, but the `secure` option, which makes cookies only work with https is not enabled, the reason being that nginx configuration for docker containers does not use SSL)

The scope of this issue is as follows:

- [ ] Make cookies secure (being set on login)
- [ ] Update docker compose nginx configuration to use SSL certificates used by front end (`s4e-web/.angular-ssl/...`)
- [ ] Update gitlab pipelines to use https protocol to access nginx for e2e purposes

**Comment by jswk** [comment] 2020-07-13 06:39
Duplicate of #589, closing. However, thanks for nice description. It's already under test in 05635052e94bf52cf020475ad8ac6aac72263ca1, unfortunately, a straightforward configuration doesn't work.

**Closed by jswk** 2020-07-13 06:39 UTC
Labels: back-end, infrastructure
